direction: ltr

meta_links:
  -
    rel: me
    link: "mailto:bianyukun1213@outlook.com"
  -
    rel: me
    link: "https://github.com/bianyukun1213"
  -
    rel: me
    link: "https://m.cmx.im/@Hollis"
  -
    rel: authorization_endpoint
    link: "https://indieauth.com/auth"
  -
    rel: webmention
    link: "https://webmention.io/his2nd.life/webmention"

microformats2:
  enable: true
  # h_card 可在 front-matter 中指定，优先于此处的配置。
  h_card:
    p_honorific_prefix: ""
    p_name: "Bian Yukun"
    p_given_name: Yukun
    p_additional_name: ""
    p_family_name: Bian
    p_honorific_suffix: ""
    p_nickname: Hollis
    u_photo: "https://bucket.hollisdevhub.com/blog/common/avatar.webp"
    u_uid:
      - 
        text: "His 2nd Life"
        link: "https://his2nd.life/"
      - 
        text: Mastodon
        link: "https://m.cmx.im/@Hollis"
      -
        text: GitHub
        link: "https://github.com/bianyukun1213"
    u_email: bianyukun1213@outlook.com

# main menu navigation
navigation:
  首页:
    icon: "fa-solid fa-house"
    link: /
  归档:
    icon: "fa-solid fa-house"
    link: /archives.html
  分类:
    icon: "fa-solid fa-house"
    link: /categories.html
  标签:
    icon: "fa-solid fa-house"
    link: /tags.html
  关于:
    icon: "fa-solid fa-house"
    link: /about.html

# 页脚备案……
icp_record:
  text: 萌ICP备20230041号
  link: "https://icp.gov.moe/?keyword=20230041"

copyright:
  # default: "cc_by_sa_4"
  default: "CC-BY-SA 4.0" # 文字，并非属性名可留空。
  cc_by_sa_4: "CC-BY-SA 4.0"

comments:
  enable: ["webmentions", "twikoo"]
  webmentions: 111
  twikoo: 123

img_handler:
  priority: 5



# config_handler:
#   priority: 5

# stylesheets loaded in the <head>
# stylesheets:
# - /css/hexo-theme-tide.css

# scripts loaded in the end of the body
# scripts:
# - /js/hexo-theme-tide.js
