direction: ltr

meta_icons:
  favicon: "/img/favicon.ico"
  apple_touch_icon: "/img/favicon.ico"

meta_links:
  -
    rel: me
    href: "mailto:bianyukun1213@outlook.com"
  -
    rel: me
    href: "https://github.com/bianyukun1213"
  -
    rel: me
    href: "https://m.cmx.im/@Hollis"
  -
    rel: authorization_endpoint
    href: "https://indieauth.com/auth"
  -
    rel: webmention
    href: "https://webmention.io/his2nd.life/webmention"

colors:
  light:
    primary: "#3F72AF"
    secondary: "#00ADB5"
    background_primary: "#FFFFFF"
    background_secondary: "#FAFAFA"
    text_primary: "#323739"
    text_secondary: "#5c6669"
    text_diminished: "#EAECED"
    text_side_bar: "#FFFFFF"
    focused_outline: "#E36209"
    link: "#3F72AF"
    link_hover: "#3F72AF"
    link_visited: "#00ADB5"
    code: "#3F72AF"
    table_border: "#E5E7EB"
    table_background_head: "#F3F3F3"
    table_background_even: "#FAFAFA"
  dark:
    primary: "#3F72AF"
    secondary: "#00ADB5"
    background_primary: "#FFFFFF"
    background_secondary: "#FAFAFA"
    text_primary: "#323739"
    text_secondary: "#5c6669"
    text_diminished: "#EAECED"
    text_side_bar: "#FFFFFF"
    focused_outline: "#E36209"
    link: "#3F72AF"
    link_hover: "#3F72AF"
    link_visited: "#00ADB5"
    code: "#3F72AF"
    table_border: "#E5E7EB"
    table_background_head: "#F3F3F3"
    table_background_even: "#FAFAFA"

microformats2:
  enable: true
  # h_card 可在 front-matter 中指定，优先于此处的配置。
  h_card:
    p_honorific_prefix: ""
    p_name: "Bian Yukun"
    p_given_name: Yukun
    p_additional_name: ""
    p_family_name: Bian
    p_honorific_suffix: ""
    p_nickname: Hollis
    u_photo: "https://bucket.hollisdevhub.com/blog/common/avatar.webp"
    u_uid:
      - 
        text: "His 2nd Life"
        link: "https://his2nd.life/"
      - 
        text: Mastodon
        link: "https://m.cmx.im/@Hollis"
      -
        text: GitHub
        link: "https://github.com/bianyukun1213"
    u_email: bianyukun1213@outlook.com
    p_note: "Just a **S**illy **B**oy."

cdn:
  font_awesome_css:
    href: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
    integrity: "sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
  jquery_js:
    src: "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
    integrity: "sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="

fonts:
  web_fonts:
    enable: true
    preconnect: "https://fonts.bunny.net"
    css_href: "https://fonts.bunny.net/css?family=jetbrains-mono:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i|ma-shan-zheng:400|noto-sans-sc:100,200,300,400,500,600,700,800,900|noto-serif-sc:200,300,400,500,600,700,800,900"
  global: "'Noto Sans SC', sans-serif"
  site_title: "'Ma Shan Zheng', handwriting"
  prose: "'Noto Serif SC', serif"
  code: "'JetBrains Mono', monospace"

# main menu navigation
navigation:
  首页:
    icon: "fa-solid fa-house"
    link: /
  分类:
    icon: "fa-solid fa-folder-open"
    link: /categories/
  标签:
    icon: "fa-solid fa-tag"
    link: /tags/
  关于:
    icon: "fa-solid fa-user"
    link: /about/
  外部:
    icon: "fa-solid fa-pen"
    link: "https://www.bing.com/"

# 页脚备案……
icp_record:
  text: 萌ICP备20230041号
  link: "https://icp.gov.moe/?keyword=20230041"

copyright:
  # default: "cc_by_sa_4"
  default: "CC-BY-SA 4.0" # 文字，并非属性名可留空。
  cc_by_sa_4: "CC-BY-SA 4.0"

comments:
  enable: ["webmentions", "twikoo"]
  webmentions: 111
  twikoo: 123

img_handler:
  priority: 5
css_modifier:
  priority: 5



# config_handler:
#   priority: 5

# stylesheets loaded in the <head>
# stylesheets:
# - /css/hexo-theme-tide.css

# scripts loaded in the end of the body
# scripts:
# - /js/hexo-theme-tide.js
