dir: ltr

meta_icons:
  favicon: "/img/favicon.ico"
  apple_touch_icon: "/img/favicon.ico"

meta_links:
  -
    rel: me
    href: "mailto:bianyukun1213@outlook.com"
  -
    rel: me
    href: "https://github.com/bianyukun1213"
  -
    rel: me
    href: "https://m.cmx.im/@Hollis"
  -
    rel: authorization_endpoint
    href: "https://indieauth.com/auth"
  -
    rel: webmention
    href: "https://webmention.io/his2nd.life/webmention"

colors:
  light:
    primary: "#3F72AF"
    secondary: "#00ADB5"
    # background_primary: "red"
    background_primary: "#FFFFFF"
    background_secondary: "#F1F1F1"
    text_primary: "#323739"
    text_secondary: "#5c6669"
    text_diminished: "#EAECED"
    text_side_bar: "#FFFFFF"
    focused_outline: "#E36209"
    link: "#3F72AF"
    link_hover: "#3F72AF"
    link_visited: "#00ADB5"
    code_inline: "#3F72AF"
    table_border: "#E5E7EB"
    table_background_head: "#F1F1F1"
    table_background_even: "#F5F5F5"
  dark:
    primary: "#3F72AF"
    secondary: "#00ADB5"
    # background_primary: "red"
    background_primary: "#FFFFFF"
    background_secondary: "#F1F1F1"
    text_primary: "#323739"
    text_secondary: "#5c6669"
    text_diminished: "#EAECED"
    text_side_bar: "#FFFFFF"
    focused_outline: "#E36209"
    link: "#3F72AF"
    link_hover: "#3F72AF"
    link_visited: "#00ADB5"
    code_inline: "#3F72AF"
    table_border: "#E5E7EB"
    table_background_head: "#F1F1F1"
    table_background_even: "#F5F5F5"

side_bar_background_image:
  # enable: false
  light: "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 56 28' width='56' height='28'%3E%3Cpath fill='%23ffffff' fill-opacity='0.05' d='M56 26v2h-7.75c2.3-1.27 4.94-2 7.75-2zm-26 2a2 2 0 1 0-4 0h-4.09A25.98 25.98 0 0 0 0 16v-2c.67 0 1.34.02 2 .07V14a2 2 0 0 0-2-2v-2a4 4 0 0 1 3.98 3.6 28.09 28.09 0 0 1 2.8-3.86A8 8 0 0 0 0 6V4a9.99 9.99 0 0 1 8.17 4.23c.94-.95 1.96-1.83 3.03-2.63A13.98 13.98 0 0 0 0 0h7.75c2 1.1 3.73 2.63 5.1 4.45 1.12-.72 2.3-1.37 3.53-1.93A20.1 20.1 0 0 0 14.28 0h2.7c.45.56.88 1.14 1.29 1.74 1.3-.48 2.63-.87 4-1.15-.11-.2-.23-.4-.36-.59H26v.07a28.4 28.4 0 0 1 4 0V0h4.09l-.37.59c1.38.28 2.72.67 4.01 1.15.4-.6.84-1.18 1.3-1.74h2.69a20.1 20.1 0 0 0-2.1 2.52c1.23.56 2.41 1.2 3.54 1.93A16.08 16.08 0 0 1 48.25 0H56c-4.58 0-8.65 2.2-11.2 5.6 1.07.8 2.09 1.68 3.03 2.63A9.99 9.99 0 0 1 56 4v2a8 8 0 0 0-6.77 3.74c1.03 1.2 1.97 2.5 2.79 3.86A4 4 0 0 1 56 10v2a2 2 0 0 0-2 2.07 28.4 28.4 0 0 1 2-.07v2c-9.2 0-17.3 4.78-21.91 12H30zM7.75 28H0v-2c2.81 0 5.46.73 7.75 2zM56 20v2c-5.6 0-10.65 2.3-14.28 6h-2.7c4.04-4.89 10.15-8 16.98-8zm-39.03 8h-2.69C10.65 24.3 5.6 22 0 22v-2c6.83 0 12.94 3.11 16.97 8zm15.01-.4a28.09 28.09 0 0 1 2.8-3.86 8 8 0 0 0-13.55 0c1.03 1.2 1.97 2.5 2.79 3.86a4 4 0 0 1 7.96 0zm14.29-11.86c1.3-.48 2.63-.87 4-1.15a25.99 25.99 0 0 0-44.55 0c1.38.28 2.72.67 4.01 1.15a21.98 21.98 0 0 1 36.54 0zm-5.43 2.71c1.13-.72 2.3-1.37 3.54-1.93a19.98 19.98 0 0 0-32.76 0c1.23.56 2.41 1.2 3.54 1.93a15.98 15.98 0 0 1 25.68 0zm-4.67 3.78c.94-.95 1.96-1.83 3.03-2.63a13.98 13.98 0 0 0-22.4 0c1.07.8 2.09 1.68 3.03 2.63a9.99 9.99 0 0 1 16.34 0z'%3E%3C/path%3E%3C/svg%3E\");"
  dark: "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 56 28' width='56' height='28'%3E%3Cpath fill='%23ffffff' fill-opacity='0.05' d='M56 26v2h-7.75c2.3-1.27 4.94-2 7.75-2zm-26 2a2 2 0 1 0-4 0h-4.09A25.98 25.98 0 0 0 0 16v-2c.67 0 1.34.02 2 .07V14a2 2 0 0 0-2-2v-2a4 4 0 0 1 3.98 3.6 28.09 28.09 0 0 1 2.8-3.86A8 8 0 0 0 0 6V4a9.99 9.99 0 0 1 8.17 4.23c.94-.95 1.96-1.83 3.03-2.63A13.98 13.98 0 0 0 0 0h7.75c2 1.1 3.73 2.63 5.1 4.45 1.12-.72 2.3-1.37 3.53-1.93A20.1 20.1 0 0 0 14.28 0h2.7c.45.56.88 1.14 1.29 1.74 1.3-.48 2.63-.87 4-1.15-.11-.2-.23-.4-.36-.59H26v.07a28.4 28.4 0 0 1 4 0V0h4.09l-.37.59c1.38.28 2.72.67 4.01 1.15.4-.6.84-1.18 1.3-1.74h2.69a20.1 20.1 0 0 0-2.1 2.52c1.23.56 2.41 1.2 3.54 1.93A16.08 16.08 0 0 1 48.25 0H56c-4.58 0-8.65 2.2-11.2 5.6 1.07.8 2.09 1.68 3.03 2.63A9.99 9.99 0 0 1 56 4v2a8 8 0 0 0-6.77 3.74c1.03 1.2 1.97 2.5 2.79 3.86A4 4 0 0 1 56 10v2a2 2 0 0 0-2 2.07 28.4 28.4 0 0 1 2-.07v2c-9.2 0-17.3 4.78-21.91 12H30zM7.75 28H0v-2c2.81 0 5.46.73 7.75 2zM56 20v2c-5.6 0-10.65 2.3-14.28 6h-2.7c4.04-4.89 10.15-8 16.98-8zm-39.03 8h-2.69C10.65 24.3 5.6 22 0 22v-2c6.83 0 12.94 3.11 16.97 8zm15.01-.4a28.09 28.09 0 0 1 2.8-3.86 8 8 0 0 0-13.55 0c1.03 1.2 1.97 2.5 2.79 3.86a4 4 0 0 1 7.96 0zm14.29-11.86c1.3-.48 2.63-.87 4-1.15a25.99 25.99 0 0 0-44.55 0c1.38.28 2.72.67 4.01 1.15a21.98 21.98 0 0 1 36.54 0zm-5.43 2.71c1.13-.72 2.3-1.37 3.54-1.93a19.98 19.98 0 0 0-32.76 0c1.23.56 2.41 1.2 3.54 1.93a15.98 15.98 0 0 1 25.68 0zm-4.67 3.78c.94-.95 1.96-1.83 3.03-2.63a13.98 13.98 0 0 0-22.4 0c1.07.8 2.09 1.68 3.03 2.63a9.99 9.99 0 0 1 16.34 0z'%3E%3C/path%3E%3C/svg%3E\");"
  # light: "url(\"data:image/svg+xml,%3Csvg width='70' height='70' viewBox='0 0 70 70' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='%23ffffff' fill-opacity='0.05' fill-rule='evenodd'%3E%3Cpath d='M0 0h35v35H0V0zm5 5h25v25H5V5zm5 5h15v15H10V10zm5 5h5v5h-5v-5zM40 5h25v25H40V5zm5 5h15v15H45V10zm5 5h5v5h-5v-5zM70 35H35v35h35V35zm-5 5H40v25h25V40zm-5 5H45v15h15V45zm-5 5h-5v5h5v-5zM30 40H5v25h25V40zm-5 5H10v15h15V45zm-5 5h-5v5h5v-5z'/%3E%3C/g%3E%3C/svg%3E\");"
  # dark: "url(\"data:image/svg+xml,%3Csvg width='70' height='70' viewBox='0 0 70 70' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='%23ffffff' fill-opacity='0.05' fill-rule='evenodd'%3E%3Cpath d='M0 0h35v35H0V0zm5 5h25v25H5V5zm5 5h15v15H10V10zm5 5h5v5h-5v-5zM40 5h25v25H40V5zm5 5h15v15H45V10zm5 5h5v5h-5v-5zM70 35H35v35h35V35zm-5 5H40v25h25V40zm-5 5H45v15h15V45zm-5 5h-5v5h5v-5zM30 40H5v25h25V40zm-5 5H10v15h15V45zm-5 5h-5v5h5v-5z'/%3E%3C/g%3E%3C/svg%3E\");"

microformats2:
  enable: true
  # h_card 可在 front-matter 中指定，优先于此处的配置。
  h_cards:
    -
      p_honorific_prefix: ""
      p_name: "Bian Yukun"
      p_given_name: Yukun
      p_additional_name: ""
      p_family_name: Bian
      p_honorific_suffix: ""
      p_nickname: Hollis
      u_photo: "https://bucket.hollisdevhub.com/blog/common/avatar.webp"
      u_uid:
        - 
          text: "His 2nd Life"
          link: "https://his2nd.life/"
        - 
          text: Mastodon
          link: "https://m.cmx.im/@Hollis"
        -
          text: GitHub
          link: "https://github.com/bianyukun1213"
      u_email: bianyukun1213@outlook.com
      p_note: "Just a **S**illy **B**oy."

cdn:
  font_awesome_css:
    href: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
    integrity: "sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
  prism_css:
    href: "https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism-tomorrow.min.css"
    integrity: "sha512-vswe+cgvic/XBoF1OcM/TeJ2FW0OofqAVdCZiEYkd6dwGXthvkSFWOoGGJgS2CW70VK5dQM5Oh+7ne47s74VTg=="
  prism_line_numbers_css:
    href: "https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/plugins/line-numbers/prism-line-numbers.min.css"
    integrity: "sha512-cbQXwDFK7lj2Fqfkuxbo5iD1dSbLlJGXGpfTDqbggqjHJeyzx88I3rfwjS38WJag/ihH7lzuGlGHpDBymLirZQ=="
  prism_line_highlight_css:
    href: "https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/plugins/line-highlight/prism-line-highlight.min.css"
    integrity: "sha512-nXlJLUeqPMp1Q3+Bd8Qds8tXeRVQscMscwysJm821C++9w6WtsFbJjPenZ8cQVMXyqSAismveQJc0C1splFDCA=="
  webmentionjs_css:
    href: "/css/third-party/webmention.css"
    integrity: ""
  prism_js:
    src: "https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js"
    integrity: "sha512-7Z9J3l1+EYfeaPKcGXu3MS/7T+w19WtKQY/n+xzmw4hZhJ9tyYmcUS+4QqAlzhicE5LAfMQSF3iFTK9bQdTxXg=="
  prism_line_numbers_js:
    src: "https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/plugins/line-numbers/prism-line-numbers.min.js"
    integrity: "sha512-BttltKXFyWnGZQcRWj6osIg7lbizJchuAMotOkdLxHxwt/Hyo+cl47bZU0QADg+Qt5DJwni3SbYGXeGMB5cBcw=="
  prism_line_highlight_js:
    src: "https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/plugins/line-highlight/prism-line-highlight.min.js"
    integrity: "sha512-255MpVHZHmxNdOj/PivQ+WSTYFjBxTMfmIszxwsJobUeaoDNUAnAQjYF5TznbiZXrXqpCy8q4QyvJzhykpof3Q=="
  # jquery_js:
  #   src: "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
  #   integrity: "sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
  pinchzoom_js:
    src: "/js/third-party/pinch-zoom.umd.min.js" # patched
    integrity: ""
  twikoo_js:
    src: "https://cdnjs.cloudflare.com/ajax/libs/twikoo/1.6.41/twikoo.all.min.js"
    integrity: "sha512-cdLlE9nnzcJXQoy9eFuzGcpQXx70rXxmUNpvrvYTAwQv2txLSdvEUs+eILIyKVFBvAoUm9iUR73ewSD3IiGZ/w=="
  webmentionjs_js:
    src: "/js/third-party/webmention.js"
    integrity: ""
  search_js:
    src: "/js/third-party/search.js"
    integrity: ""

fonts:
  web_fonts:
    enable: true
    preconnect: "https://fonts.bunny.net"
    # css_href: "https://fonts.bunny.net/css?family=jetbrains-mono:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i|ma-shan-zheng:400|noto-sans-sc:100,200,300,400,500,600,700,800,900|noto-serif-sc:200,300,400,500,600,700,800,900"
    css_href: "https://fonts.bunny.net/css?family=ma-shan-zheng:400|noto-sans-sc:100,200,300,400,500,600,700,800,900|noto-serif-sc:200,300,400,500,600,700,800,900"
    # css_href: "https://fonts.bunny.net/css?family=ma-shan-zheng:400|noto-sans-sc:100,200,300,400,500,600,700,800,900|noto-serif-sc:200,300,400,500,600,700,800,900|zcool-kuaile:400"
  global: "'Noto Sans SC', sans-serif"
  # global: "'ZCOOL KuaiLe', sans-serif"
  site_title: "'Noto Sans SC', sans-serif"
  # site_title: "'Ma Shan Zheng', handwriting"
  site_subtitle: "'Ma Shan Zheng', handwriting"
  prose: "'Noto Serif SC', serif"

# main menu navigation
navigation:
  首页:
    icon: "fa-solid fa-house"
    link: /
  分类:
    icon: "fa-solid fa-folder-open"
    link: /categories/
  标签:
    icon: "fa-solid fa-tag"
    link: /tags/
  关于:
    icon: "fa-solid fa-user"
    link: /about/
  外部:
    icon: "fa-solid fa-pen"
    link: "https://www.bing.com/"
  测试:
    icon: "fa-solid fa-house"
    link: /test-page/

# 页脚备案……
icp_record:
  text: 萌ICP备20230041号
  link: "https://icp.gov.moe/?keyword=20230041"

generated_by_hexo_and_theme_tide: true

copyright:
  # default: "cc_by_sa_4"
  default: "CC-BY-SA 4.0" # 文字，并非属性名可留空。
  cc_by_sa_4: "CC-BY-SA 4.0"

interactions:
  enable: ["twikoo", "webmentionjs"]
  twikoo:
    env_id: "https://twikoo.his2nd.life"
    region: ""
  webmentionjs:
    wordcount: -1
    max_webmentions: 30
    prevent_spoofing: false
    sort_by: "published"
    sort_dir: "up"
    comments_are_reactions: false


image_handler:
  priority: 5
table_handler:
  priority: 5
css_modifier:
  priority: 5
page_modifier:
  priority: 5

toc:
  enable: true
  list_number: false
search: true
word_counter: true
list_separator: ", "
item_marker_begin: "["
item_marker_end: "]"

# config_handler:
#   priority: 5

# stylesheets loaded in the <head>
# stylesheets:
# - /css/hexo-theme-tide.css

# scripts loaded in the end of the body
# scripts:
# - /js/hexo-theme-tide.js
